### ISSUE TITLE
Using fitvids with Vue

### ISSUE THREAD

**Issue by lukeliasi** [rosszurowski/fitvids#5]
I am using Vuejs and have included this via npm and get:
`Uncaught TypeError: el.querySelectorAll is not a function`

I am including it in my component like so (using bable):
```
import Vue from 'vue'
import Fitvids from 'fitvids'
Vue.use(Fitvids)
```

The error comes from what is being returned in this function.
```
function queryAll (el, selector) {
	if (typeof el === 'string') {
		selector = el
		el = document
	}
	return Array.prototype.slice.call(el.querySelectorAll(selector))
}
```
The library works fine when I include the file manually, eg:
`<script src="/src/assets/js/fitvids.min.js"></script>`

any ideas?

**Comment by rosszurowski** [comment]
You're calling fitvids as though it was [a Vue plugin](https://vuejs.org/v2/guide/plugins.html#Using-a-Plugin), like [vue-router](https://github.com/vuejs/vue-router) or [vue-touch](https://github.com/vuejs/vue-touch). Fitvids is a generic javascript library, so you need to use it differently.

When you're initializing your top-level Vue app, just add a call to `fitvids` in [the Vue `mounted` event](https://vuejs.org/v2/guide/instance.html#Instance-Lifecycle-Hooks).

```js
import Vue from 'vue'
import fitvids from 'fitvids'

var app = new Vue({
  // Your Vue code
  mounted: function () {
    fitvids()
  }
})
```

Keep in mind, `fitvids()` will only wrap videos that are on the page when the function is called. If you add new videos later, you'll need to call `fitvids()` again to wrap them. It's smart enough to only wrap the new videos.

**Comment by ianhobbs** [comment]
Thanks this tip helped me as well. Would suggest this get elevated into the read-me.
