### ISSUE TITLE
Would adding a callback be considered useful ?

### ISSUE THREAD

**Issue by Lucassifoni** [rosszurowski/fitvids#6]
Hi,
I forked to add (mainly for myself) the possibility to add a callback to the fitvids call, taking the newly created container as an argument.
Would you consider this use-specific, or would you be interested in a PR (in this case, I'd take care of adding tests for this) ?
Have a nice day.

**Comment by rosszurowski** [comment]
Hi! I'm definitely not opposed to it.

Do you mind sharing an example of how you would use the return value? I just want to understand what you're trying to do.

**Comment by Lucassifoni** [comment]
In some Vue app I'm developing, a container can contain layered absolute-positioned divs, sometimes above a static one, sometimes not, and in those cases, I need to retrieve the padding value to also use it on the parent container.
But I'm calling fitvids on specific elements to avoid a global treatment of video elements, so, in this use case, the return value serves my purpose.
I was also wondering if I could switch to a global fitvids() call, given I'm passing the callback an array looking like this mock : 

```
[
  {
    el,
    cssValue: 'xx,x%',
    aspectRatio: 0.xxx,
  },
  ...
]
```

To further re-use those values.

To be fair, this situation came from an undiagnosed need for videos when this app was drafted, and a lack of time & budget to refactor before the first delivery. (So, it would help me expand on a hack.)

**Comment by rosszurowski** [comment]
Hmm. I'm not sure I follow. You want to get the `paddingTop` of each of the wrappers (ie. the number [defined here](https://github.com/rosszurowski/fitvids/blob/master/index.js#L84))? Why do you need to use it on the parent container?

Could you give a more complete example? It might make it more clear. (Sorry for the confusion!)

**Comment by Lucassifoni** [comment]
I'm using some full-width, 8/5 aspect-ratio containers that can contain a mix of those items :  
- Two picture containers that are both a 4/5 ratio, side-to-side, that combined have a fixed ratio of 8/5
- A 8/5 full-width "cover" picture that is hiding everything below, absolutely positioned
- A video, either directly under this cover in case there are no picture containers, either revealable with a "show video" button.

In the case there's a "cover" and a video, but no picture containers, I use a padding hack to attain this 8/5 ratio, even there are no statically positioned items inside this container. When the cover fades out, in case the video has an aspect-ratio smaller in height than 8/5, the margins below the container get too high, so I'm retrieving the padding value used by the video to correct my container's padding.

I should provide you a fiddle. Sadly, we have no time to rework the markup for a last-minute edge case, so I'm just hooking into the video reveal step to get its fitvids-provided padding value from the DOM. To clean this a little bit, I'd like to get a return value from fitvids.

But I'm starting to think this is really too use-case-specific to merge a PR.
Anyway, thanks for your answers and your work, have a nice day !

**Comment by rosszurowski** [comment]
Yeah, I think this is a bit too specific of a case for this library.

I'm totally happy to change the API, and make/accept PRs, but I just want to make sure they're broadly applicable first.

Thanks for reaching out to ask though, and feel free to re-open if you find this case cropping up more and more!
